apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: <ServiceName>
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            cpu: "1"
            memory: 300Mi
          limits:
            cpu: "4.5" 
            memory: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-name
  labels:
    name: my-name
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: my-name
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done",
            ]
          resources:
            requests:
              cpu: "2"
              memory: "5.5Mi"
        - name: init-mydb
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done",
            ]

      containers:
        - image: ipedrazas/docmock
          name: my-name
          resources:
            requests:

              cpu: "120"
              memory: "5.543Mi"
            limits:
              cpu: "0.3"
              memory: "1Ti"
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          env:
            - name: ENVVARNAME
              value: ENVVARVALUE
          ports:
            - containerPort: 5000
              name: my-name
          volumeMounts:
            - mountPath: /data
              name: data
        - image: second-img/blah
          name: my-name
          resources:
            requests:
              cpu: "127m"
              memory: "1.567Gi"
            limits:
              cpu: "1500m"
              memory: "2.5Gi"
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          env:
            - name: ENVVARNAME
              value: ENVVARVALUE
          ports:
            - containerPort: 5000
              name: my-name
          volumeMounts:
            - mountPath: /data
              name: data

      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always
---
apiVersion: v1
kind: Namespace
metadata:
  name:  name
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  labels:
    app: myapplication
data:
  my-key: my-value
